services:
  paprika-pg:
    image: postgres:18-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql
    env_file:
      - ./backend/.env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  paprika-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DJANGO_ENV: development
    init: true
    volumes:
      - ./backend:/code
      - media_volume:/code/media
    env_file:
      - ./backend/.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      paprika-pg:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_volume:
  media_volume:
